# Generated by Django 5.2.8 on 2025-12-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='comment',
            field=models.TextField(blank=True, help_text="Commentaire de l'enseignant", null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
