# Generated by Django 5.2.8 on 2025-12-09 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_students_alter_subject_teacher'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day', 'start_time'], 'verbose_name': 'Créneau horaire', 'verbose_name_plural': 'Créneaux horaires'},
        ),
        migrations.AlterModelOptions(
            name='weeklyschedule',
            options={'verbose_name': 'Emploi du temps', 'verbose_name_plural': 'Emplois du temps'},
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='classes.class'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('schedule', 'day', 'start_time', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyschedule',
            unique_together={('class_assigned',)},
        ),
    ]
