# Generated by Django 5.2.8 on 2025-12-09 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_timeslot_options_alter_weeklyschedule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyschedule',
            options={'verbose_name': 'Emploi du temps de classe', 'verbose_name_plural': 'Emplois du temps des classes'},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('teacher', 'day', 'start_time', 'end_time')},
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='schedule.weeklyschedule'),
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.IntegerField(default=0, help_text="Nombre total d'heures par semaine")),
                ('max_hours', models.IntegerField(default=20, help_text="Nombre maximum d'heures par semaine")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emploi du temps enseignant',
                'verbose_name_plural': 'Emplois du temps enseignants',
            },
        ),
        migrations.AddField(
            model_name='timeslot',
            name='teacher_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='schedule.teacherschedule'),
        ),
    ]
