# Generated by Django 5.2.8 on 2025-12-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_weeklyschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherschedule',
            name='max_hours',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text="Nombre maximum d'heures par semaine", max_digits=5),
        ),
        migrations.AlterField(
            model_name='teacherschedule',
            name='weekly_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Nombre total d'heures par semaine", max_digits=5),
        ),
    ]
