# Generated by Django 5.2.9 on 2026-01-04 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_students_alter_subject_teacher'),
        ('live', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveparticipant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='livesession',
            options={'ordering': ['-start_time'], 'verbose_name': 'Session Live', 'verbose_name_plural': 'Sessions Live'},
        ),
        migrations.AlterModelOptions(
            name='screenshare',
            options={'ordering': ['-started_at'], 'verbose_name': "Partage d'écran", 'verbose_name_plural': "Partages d'écran"},
        ),
        migrations.AlterField(
            model_name='liveparticipant',
            name='audio_enabled',
            field=models.BooleanField(default=True, help_text='Micro activé?'),
        ),
        migrations.AlterField(
            model_name='liveparticipant',
            name='is_presenter',
            field=models.BooleanField(default=False, help_text="True si c'est l'enseignant ou un présentateur"),
        ),
        migrations.AlterField(
            model_name='liveparticipant',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Quand l'utilisateur a rejoint"),
        ),
        migrations.AlterField(
            model_name='liveparticipant',
            name='left_at',
            field=models.DateTimeField(blank=True, help_text="Quand l'utilisateur a quitté (NULL si toujours présent)", null=True),
        ),
        migrations.AlterField(
            model_name='liveparticipant',
            name='screen_sharing',
            field=models.BooleanField(default=False, help_text="Partage d'écran activé?"),
        ),
        migrations.AlterField(
            model_name='liveparticipant',
            name='session',
            field=models.ForeignKey(help_text="Session à laquelle participe l'utilisateur", on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live.livesession'),
        ),
        migrations.AlterField(
            model_name='liveparticipant',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur qui participe', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='liveparticipant',
            name='video_enabled',
            field=models.BooleanField(default=True, help_text='Caméra activée?'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description optionnelle'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Heure de fin (NULL si pas terminée)', null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='max_participants',
            field=models.IntegerField(default=50, help_text='Nombre maximum de participants'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='meeting_id',
            field=models.CharField(editable=False, help_text='ID unique générée automatiquement pour la réunion', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Heure de création/démarrage'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmée'), ('live', 'En cours'), ('ended', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', help_text='Statut actuel de la session', max_length=20),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='subject',
            field=models.ForeignKey(help_text='Matière pour laquelle la session est créée', on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='classes.subject'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='teacher',
            field=models.ForeignKey(help_text='Enseignant qui anime la session', limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='title',
            field=models.CharField(help_text='Titre de la session', max_length=200),
        ),
        migrations.AlterField(
            model_name='screenshare',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text="Quand le partage s'est arrêté", null=True),
        ),
        migrations.AlterField(
            model_name='screenshare',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Le partage est-il en cours?'),
        ),
        migrations.AlterField(
            model_name='screenshare',
            name='session',
            field=models.ForeignKey(help_text="Session dans laquelle l'écran est partagé", on_delete=django.db.models.deletion.CASCADE, related_name='screen_shares', to='live.livesession'),
        ),
        migrations.AlterField(
            model_name='screenshare',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Quand le partage a commencé'),
        ),
        migrations.AlterField(
            model_name='screenshare',
            name='stream_id',
            field=models.CharField(help_text='ID du stream WebRTC', max_length=200),
        ),
        migrations.AlterField(
            model_name='screenshare',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur qui partage son écran', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='liveparticipant',
            index=models.Index(fields=['session', 'left_at'], name='live_livepa_session_a0cbc2_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['teacher', '-start_time'], name='live_livese_teacher_c47a44_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['status'], name='live_livese_status_bf6848_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['meeting_id'], name='live_livese_meeting_db9c50_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshare',
            index=models.Index(fields=['session', 'is_active'], name='live_screen_session_175237_idx'),
        ),
    ]
