# Generated by Django 5.2.9 on 2026-01-05 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_alter_liveparticipant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveparticipant',
            name='agora_uid',
            field=models.BigIntegerField(blank=True, help_text='UID unique pour Agora dans cette session', null=True),
        ),
        migrations.AddIndex(
            model_name='liveparticipant',
            index=models.Index(fields=['agora_uid'], name='live_livepa_agora_u_5026ed_idx'),
        ),
    ]
